apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: kube-system
stringData:
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:h1v0RUARjuGVpgfpyHIgCRV384a7+mew8FPbshL3sqGoC8bEqitJ8w==,iv:axLdLmx02xItIQzZA1zdLYyhhAEuwy4ICTAv87VfYWE=,tag:VIbURLWxvK47shI2hVBegQ==,type:str]
sops:
    age:
        - recipient: age1cwwvujgvczvztye0z5znc9ryu6zx2nk58ghq6rxhqdc5tt5v5cdqweq7tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RjBwNWtWQTZpS2NaVXZ3
            NU4vQlJFdDJxbDZRdnNjbGQvZE4wQnBrZ1VBCmVVU1VaSWJBQWlQSzVUSlFJK3lW
            QUlETTNpZjFVUG5lWVhJUmlpdm1MdWsKLS0tIFdNQVpTditkYWZLNkRHSmtvTGVH
            TThLU3RkRzlXNDgydnBocy8xVXQ3b2cK4iz3ZGaqekLTsbYNJL6QUevcDh8ELmG5
            l9qiBZzZ+izpgaW1LKDetPzeZRvuDsQoHxK1Z6NLLU2iRA07ST04dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T17:42:11Z"
    mac: ENC[AES256_GCM,data:hTukItukoY+vK8XkZZ1yFPGtliu7HPrc1hrV4UzXE3P2Z1XT4MUSVSaAQkdYHF+clRFp504HfAvk/9aGUoGP0d/sBghB7Mq5A8+HC9oDPaU/Bv9WqwXwxBfk/watKT5xu+kDvXgEwOSc2Am0rjQtIFv12H3d39FbDcsqwvW2z6Q=,iv:5Lrz9z+rStZ5yrw415oUkYxAFZw2+ORoqZMoTjl706s=,tag:I/0VPD3eWA/A7NmYCjMttw==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
