apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:jaSiOpn+OElXUTlZv9tWLUUrQgNj4VnBEeceyWAaPvpnKt0mGpwXIw==,iv:NXPHBm/3RwmxZMGRga1KjzL7F4r/vNqtgX8Ycwr1sXI=,tag:y+AApG0FGHz/JTsnYytyKw==,type:str]
sops:
    age:
        - recipient: age1cwwvujgvczvztye0z5znc9ryu6zx2nk58ghq6rxhqdc5tt5v5cdqweq7tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbnBkdGg5M3Z2QlF1MnpY
            Z1A3cVgvWk82aElyMzV3cEo0MXFVVVNwSVdZClpoSURVV3U4UlJibGYzZEFLNk9a
            YlRhV284YkZaazBzZEZzWTVIa3pKQncKLS0tIGgwNEZzZHM5UGdibU1NUWt2bHRM
            UE9SVUpHMGtQR0U1dTVJc21rVjA2R3MKzr8wN9+FEl7vMIX3oD9uKmgpLB8OIxyO
            P/dKG4TKJoNAMqoX/sE76jCGYDwtNXqbLTwHQe3j2YI49zUfVlILJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T23:55:22Z"
    mac: ENC[AES256_GCM,data:m+2orIK6NLK3I/3WbrLwsn0I5490KLj8wkPGmEOoEsNZ96fPak1H18Ukq5h9qW7G91WIE2v23E3fK1NErsgmBqKBlb1UgMugvQG4yPcUBkQMMF/YJP0JNklb6fqPGbLccRYeMslU9lOtqKkBibLq/U3R0GSNTHIk6WgbHfr9bcw=,iv:FBO5gg0l4V+Bba41Cvuw7aD2g4GGe3HbIRVGxnvgcl0=,tag:LhVMUQOwfl9Je6U/kvIXJg==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
