apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4NjdGGAkZElU9GUUvFoczBoiSJQ=,iv:vni8jrHwF0G1GtWGaamnzu6dPZvviV0ZPRjvhdy4ex8=,tag:u8xKqT79j1BpTINMiOINSw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:xcVDM/xsUgfzs2V14uD+iuKN,iv:2n9fPcZoEYV5iAWSbDzVPQ1yVyqerXwvwYV6hCRQT4I=,tag:Tg8TMbDq882j6HmTOGW5ew==,type:str]
    SECRET_TRAEFIK_DASHBOARD_HOSTNAME: ENC[AES256_GCM,data:rD5hBxbgagOikZ+ZbDVacYjRlW1KNQUulIU=,iv:4jZI2FGkAPzl29k/TwryfiL4McK75GP6ulP6Sb185RA=,tag:edsAUPj3tjqvKze9WgaQFA==,type:str]
sops:
    age:
        - recipient: age1cwwvujgvczvztye0z5znc9ryu6zx2nk58ghq6rxhqdc5tt5v5cdqweq7tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYWVMMEhJZWl4Nk5SNzNy
            WDRsdUwzTmIrRlNFNDNzc2l4dVJsYTRJS2tjCkVTRmlXWmxSTTJ2akkxREN4NlpM
            N2VXOC9FV2FLWWFkdFZsUzM2ZE43QmMKLS0tIElneWhhREVhc21CUExEK0t6dzRP
            Um9GcTdCSHEwZ3kyR0NMV2QzczduQm8KRc/yshw2BREqgvVHTObfswrXgXlrqXq4
            Z906iQLS4R2VxJWXqx4FrKnRKhA3mL+9S7FrCCTOEqnOUgsKNxvJYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T18:22:43Z"
    mac: ENC[AES256_GCM,data:NFw47I36CWHfN56lH1OIrSPsvBGiqY1amuO7YOZ1d/kKVB/0xXrpmQnUbvCF7Ky8McVZ9LpsMX/5mY9AENfPaI/hDF51OZgWdFV7/vXJn/2yaoypoz6u2qm5KyJBa9mZQHYVv7TCcuQvJ36y4Q9YOTuocyTxT1fA/dNhRCIKPbU=,iv:8LRU1pj9UV7pTYDbAooVYEza9aTA4+6OReovYYUSYjQ=,tag:DMG4ONPKg4GtM6S2h/sUsw==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
