apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4I9LvnEvLwS7niSgIobhxJyEdw8=,iv:91qCCtISrlSaVs5mlj1CquO3N7Gp6wpbNz/cPkMbHzw=,tag:LqYiskrRBhuivcbUtpzt+A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/12JpReGfbE85p2k0ylazkQ/,iv:9bgMjtvnLBTauwLsgF/PIk4HeIIcuhttjfwWBVVjaZI=,tag:7CX5AFzC37/V5Z4LBGCbFA==,type:str]
    SECRET_TRAEFIK_DASHBOARD_HOSTNAME: ENC[AES256_GCM,data:hcLa2reLrt48dch4jZbHwzTl1wLM06COf+s=,iv:ahVNop1Va/tFrfCyXYjzky41XcMhOmUF1m2DVrLutno=,tag:B/mqfVBDSWKyhpTBwpnvyw==,type:str]
    SECRET_LONGHORN_DASHBOARD_HOSTNAME: ENC[AES256_GCM,data:eRtEwE3L+GCw7fig4bjPqBFUOm31H6sd5g28,iv:M/d/uGnZhi/0NKkymgxl3Vi+nLijHzGjpYekTlw4li4=,tag:Y9iWuBxbteeaxjd5JplrLw==,type:str]
sops:
    age:
        - recipient: age1cwwvujgvczvztye0z5znc9ryu6zx2nk58ghq6rxhqdc5tt5v5cdqweq7tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV1FvOTBJNkJ0QUhoMVVq
            N0pTcThpcEJWWkFPdEhXRm5zanVyNStudnhZCnpBM2txYzRXS3ZQcUVTUmtuekZj
            NU5NT3U5SUxOcFJMNDRyWS9LOUtocHMKLS0tIFl2ZjVKNm03ZTRmbjhDK2ZxcmZa
            SVZCbDdPV3U2ZXA5elF2azkyanhNSjAKJYbUYXUyoi1Y7UFElg3KtCxGSEm262oX
            4o4WosECSMTFoBj2+ruNJ/tkDC76vTl/t8HLj4EnXxpN1A+pgwxQzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T21:16:13Z"
    mac: ENC[AES256_GCM,data:FaY6kxAWGPtK1dZ38K8NFTg5vhfkWjZ1Mwr795n+6TLwtVBfMYSlmPncHd8o71D6hZwowTpVKwTKirr1GeSFBUBYuNz6/RqQlJ8AR5B7QckqLdOCqAZZKzFOk/K1lQTOXQQ8X/lzm42vM7yyWAoaqzUeJsNppaKvKBmbHKd4Awg=,iv:ZL3HxyXXTltKO2YtCNOFIK184nZEkEOP1pj+k8gdQA8=,tag:OdvjKyYLN/sOK57NpVMWMQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
