---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-k8s
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: master
  url: https://github.com/dwright134/homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-k8s
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-k8s