---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  chart:
    spec:
      chart: node-feature-discovery
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-chart
      version: v0.17.3
  interval: 1m0s
