---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: namespaces
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# install NFD via Helm (creates CRDs)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfd
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/core/node-feature-discovery/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: node-feature-discovery
      namespace: node-feature-discovery
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: nodefeaturerules.nfd.k8s-sigs.io
---
# apply NodeFeatureRule CRs after CRD exists
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfd-rules
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/core/node-feature-discovery/rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: nfd