---
clusterName: ${clusterName}
talosVersion: v1.10.7
kubernetesVersion: v1.33.3
endpoint: https://${clusterName}.${domainName}:6443
allowSchedulingOnMasters: true
patches: 
  - |- 
    cluster:
      discovery:
        enabled: true
    machine:
      network:
        extraHostEntries:
          - aliases:
            - ${clusterName}.${domainName}
            ip: ${clusterEndpointIP}
nodes:
  - hostname: cp01.${clusterName}.${domainName}
    ipAddress: 172.16.2.113
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/lib/longhorn
                type: bind
                source: /var/lib/longhorn
                options:
                  - bind
                  - rshared
                  - rw
          disks:
            - device: /dev/sdb # The name of the disk to use.
              partitions:
                - mountpoint: /var/lib/longhorn # Where to mount the partition.
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/qemu-guest-agent

