---
clusterName: ${clusterName}
talosVersion: v1.11.0
kubernetesVersion: v1.33.4
endpoint: https://172.16.2.145:6443
allowSchedulingOnMasters: true
patches: 
  - |- 
    cluster:
      discovery:
        enabled: true
      extraManifests:
        - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
        - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: true
      files:
        - content: |
            [metrics]\n address = \"0.0.0.0:11234\"\n
          path: /var/cri/conf.d/metrics.toml
          op: create
nodes:
  - hostname: cp01
    ipAddress: 172.16.2.145
    controlPlane: true
    nodeLabels:
      gpu: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eno2
        dhcp: true
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/lib/longhorn
                type: bind
                source: /var/lib/longhorn
                options:
                  - bind
                  - rshared
                  - rw
          disks:
            - device: /dev/nvme0n1 # The name of the disk to use.
              partitions:
                - mountpoint: /var/lib/longhorn # Where to mount the partition.
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/tailscale
  - hostname: cp02
    ipAddress: 172.16.2.147
    controlPlane: true
    nodeLabels:
      gpu: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eno2
        dhcp: true
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/lib/longhorn
                type: bind
                source: /var/lib/longhorn
                options:
                  - bind
                  - rshared
                  - rw
          disks:
            - device: /dev/nvme0n1 # The name of the disk to use.
              partitions:
                - mountpoint: /var/lib/longhorn # Where to mount the partition.
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/tailscale
  - hostname: cp03
    ipAddress: 172.16.2.151
    controlPlane: true
    nodeLabels:
      gpu: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eno2
        dhcp: true
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/lib/longhorn
                type: bind
                source: /var/lib/longhorn
                options:
                  - bind
                  - rshared
                  - rw
          disks:
            - device: /dev/nvme0n1 # The name of the disk to use.
              partitions:
                - mountpoint: /var/lib/longhorn # Where to mount the partition.
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/tailscale
controlPlane:
  nameservers:
    - 1.1.1.1
    - 8.8.8.8
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuthKey}
