---
clusterName: ${clusterName}
talosVersion: v1.10.6
kubernetesVersion: v1.33.3
endpoint: https://${clusterName}.${domainName}:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none
patches: 
  - |- 
    cluster:
      discovery:
        enabled: true
      network:
        dnsDomain: ${domainName}
    machine:
      certSANs:
        - ${clusterEndpointIP}
      kubelet:
        extraArgs:
          rotate-server-certificates: true
      network:
        kubespan:
          enabled: true
        extraHostEntries:
          - aliases:
            - ${clusterName}.${domainName}
            ip: ${clusterEndpointIP}
      files:
        - content: |
            [metrics]\n address = \"0.0.0.0:11234\"\n
          path: /var/cri/conf.d/metrics.toml
          op: create
nodes:
  - hostname: cp01.${clusterName}.${domainName}
    ipAddress: 172.16.2.145
    controlPlane: true
    machineSpec:
      arch: amd64
      mode: metal
      bootMethod: disk-image
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/lib/longhorn
                type: bind
                source: /var/lib/longhorn
                options:
                  - bind
                  - rshared
                  - rw
          disks:
            - device: /dev/nvme0n1 # The name of the disk to use.
              partitions:
                - mountpoint: /var/lib/longhorn # Where to mount the partition.
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/nvme-cli
            - siderolabs/tailscale
            - siderolabs/util-linux-tools
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=${tsAuthKey}
  - hostname: cp02.${clusterName}.${domainName}
    ipAddress: 172.16.2.147
    controlPlane: true
    machineSpec:
      arch: amd64
      mode: metal
      bootMethod: disk-image
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/lib/longhorn
                type: bind
                source: /var/lib/longhorn
                options:
                  - bind
                  - rshared
                  - rw
          disks:
            - device: /dev/nvme0n1 # The name of the disk to use.
              partitions:
                - mountpoint: /var/lib/longhorn # Where to mount the partition.
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/nvme-cli
            - siderolabs/tailscale
            - siderolabs/util-linux-tools
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=${tsAuthKey}
  - hostname: cp03.${clusterName}.${domainName}
    ipAddress: 172.16.2.154
    controlPlane: true
    machineSpec:
      arch: amd64
      mode: metal
      bootMethod: disk-image
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/lib/longhorn
                type: bind
                source: /var/lib/longhorn
                options:
                  - bind
                  - rshared
                  - rw
          disks:
            - device: /dev/nvme0n1 # The name of the disk to use.
              partitions:
                - mountpoint: /var/lib/longhorn # Where to mount the partition.
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/nvme-cli
            - siderolabs/tailscale
            - siderolabs/util-linux-tools
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=${tsAuthKey}
controlPlane:
  patches:
    - |-
      cluster:
        apiServer:
          certSANs:
            - ${clusterEndpointIP}
        proxy:
          disabled: true        