---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: networking
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 37.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: [websecure]
        matchRule: Host(`traefik.home.danobytes.com`)
        tls:
          secretName: cluster-domain-certificate-secret 
